### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#4]
Here's a Cookbook/Recipes page design I worked a bit on today. It should show the general idea of what we can aim for (feedback welcome!)

https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=166%3A386

**Comment by sw-yx** [comment]
checking it out :)

**Comment by kevmodrome** [comment]
This is what I've come up with when it comes to the Component index page (relevant to #5). I think the most important stuff are here. An image, last update, tags as well as a short description and the title. Any things that might be missing?
 
![componentindexpage_v1](https://user-images.githubusercontent.com/534488/78989949-5ce1b380-7b35-11ea-894b-673f3a515f0c.png)

**Comment by Wolfr** [comment]
I took this and tweaked it a bit.

![image](https://user-images.githubusercontent.com/12690/79018235-9802d780-7b73-11ea-8ae0-6f66ef8b6ca2.png)

We had a discussion on Discord about which filters we need which is unresolved.

Just posting here for posterity.

**Comment by Wolfr** [comment]
Also, my Figma link to a file where I merged the Svelte Society day design with the components page and the cookbook page. Needs some detailed work on types styles etc. but this gives you an idea.

https://www.figma.com/file/iCHWpdoox2Ls3NnfujVdMz/Svelte-Society?node-id=10%3A290

**Comment by dhonx** [comment]
Great! I will take a look

**Comment by sw-yx** [comment]
just repeating what i mentioned on the discord - we should have a plan for components that dont have images. either due to lack of visual aspect or just missing data entry

**Comment by sw-yx** [comment]
think we still have some parts to go here but the latest work is https://github.com/svelte-society/sveltesociety.dev/pull/88 and now https://github.com/svelte-society/sveltesociety.dev/pull/90
